#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $NET64PLUSDIR = "/root/net64plus-server";
my $SCREENCMD = "/usr/bin/screen";
my $NET64PLUSEXE = "/usr/local/bin/pm2 start ./dist --name=\"net64 server\"";

# No changes below here...

my $exists = "";

# Set ENV vars
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep net64plus-server|grep -v grep|grep -v startnet64plus`;

# check if net64plus server process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $NET64PLUSDIR;
	# check if net64plus server process is running
	$running=`ps ax|grep net64plus-server|grep -v grep|grep -v startnet64plus`;
	if ($running eq "")
	{
		print "net64plus server not running\n";
		# See if they want the server started
		if (! -f "$NET64PLUSDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="net64plus server Down, Restarting: $datestring";
			open(OUTF, ">>$NET64PLUSDIR/Net64PlusServerScreen.log") || die "Unable to open $NET64PLUSDIR/Net64PlusServerScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $NET64PLUSDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S net64plusServer -d -U -m $NET64PLUSEXE");
		}
	}
	# Sleep for 5 minutes before checking again
	sleep(300);
}
exit(0);
